#!/bin/sh

VT="$(tty | sed 's|/dev/tty||')"
ORIG_VT="1"
if [ -t 0 ]; then
	chvt "$VT"
fi

# Run initial setup
if ! /usr/lib/userconf-pi/userconf-service; then
	echo "userconf-service failed, exiting Beepy initial setup"
	chvt "$ORIG_VT"
	exit 1
fi

# Enable autologin
whiptail --infobox "Enabling auto-login for $FIRST_USER" 20 40
FIRST_USER="$(getent passwd 1000 | cut -d: -f1)"
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --skip-login --nonewline --noissue --autologin $FIRST_USER --noclear %I $TERM
EOF

# Add user to beepy HW group
groupadd beepy_hw ||:
usermod -aG beepy_hw $FIRST_USER

# Configure driver to use HW group and add quiet flag
HW_GID="$(getent group beepy_hw | cut -d: -f3)"
sed -i "s/rootwait/quiet rootwait beepy-kbd.sysfs_gid=$HW_GID/" \
	/boot/firmware/cmdline.txt

# Copy default configs again
su - $FIRST_USER -c "cp /etc/skel/.* ~/"

# Add nmtui prompt to first boot
cat > /etc/profile.d/zz-nmtui.sh << 'EOF'
#!/bin/bash
(
echo "Waiting for NetworkManager..."
for i in $(seq 1 5); do
	if systemctl --quiet is-active NetworkManager; then
		sudo monoset 127 nmtui-connect ||:
		sudo rm -f /etc/profile.d/zz-nmtui.sh ||:
		exit 0
	fi
	sleep 1
done
)
EOF
chmod +x /etc/profile.d/zz-nmtui.sh

# Expand root filesystem
whiptail --infobox "Expanding root filesystem to fill SD card" 20 40
raspi-config --expand-rootfs

# Disable remounting of boot partition
sed -i '/\/boot\/firmware/ s/^/# /' \
	/etc/fstab

# Disable raspi-config automatic service to save boot time
whiptail --infobox "Optimizing boot services" 20 40
systemctl daemon-reload
systemctl disable raspi-config

# Update firmware if required
/usr/lib/userconf-pi/beepy-firstboot-update
whiptail --infobox "Beepy set up complete, rebooting" 20 40
chvt "$ORIG_VT"
reboot
