#!/bin/sh

VT="$(tty | sed 's|/dev/tty||')"
ORIG_VT="1"
if [ -t 0 ]; then
	chvt "$VT"
fi

# Run initial setup
if ! /usr/lib/userconf-pi/userconf-service; then
	echo "userconf-service failed, exiting Beepy initial setup"
	chvt "$ORIG_VT"
	exit 1
fi

# Enable autologin
whiptail --infobox "Enabling auto-login for $FIRST_USER" 20 40
FIRST_USER="$(getent passwd 1000 | cut -d: -f1)"
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --skip-login --nonewline --noissue --autologin $FIRST_USER --noclear %I $TERM
EOF

# Add user to beepy HW group
groupadd beepy_hw ||:
usermod -aG beepy_hw $FIRST_USER

# Configure driver to use HW group and add quiet flag
HW_GID="$(getent group beepy_hw | cut -d: -f3)"
sed -i "s/rootwait/quiet rootwait beepy-kbd.sysfs_gid=$HW_GID/" \
	/boot/firmware/cmdline.txt

# Default impala configuration
mkdir -p /etc/skel/.config/impala/
cat > /etc/skel/.config/impala/config.toml << EOF
unicode = false
monochrome = true

[station]
auto_scan = true
EOF
mkdir -p /root/.config/impala/
cat > /root/.config/impala/config.toml << EOF
unicode = false
monochrome = true

[station]
auto_scan = true
EOF

# Copy default configs again
su - $FIRST_USER -c "cp -r /etc/skel/.* ~/"

# Add interactive setup to first boot
cat > /etc/profile.d/zz-interactive-firstboot.sh << 'EOF'
#!/bin/bash
(

# Key information
monoset 127 whiptail --title "Typing symbols" --msgbox "\
* For numbers or symbols printed on\n\
  the keycaps, press Alt, then the\n\
  letter key.\n\n\
* For Tab, press Alt, then Enter.\n\n\
* View the Symbol keymap by holding\n\
  the Sym key for 1 second. To enter\n\
  a symbol, press Sym, then the\n\
  letter key.\n\n\
For details on sticky modifier keys,\n\
see the Beepy keyboard documentation\n\
or run \`man beepy-kbd\`\
" 20 40

# Touch information
monoset 127 whiptail --title "Meta mode and touchpad" --msgbox "\
\"Meta mode\" is a modal layer to send\n\
cursor keys and scroll.\n\n\
* Hold the Berry key for 1 second\n\
  to view the Meta mode keymap,\n\
  including arrow keys.\n\
* Press Back to exit Meta mode.\n\
* Hold Shift for temporary touchpad\n\
  until Shift released.\n\
* Click touchpad for persistent \n\
  touchpad until Back key pressed.\n\
* While on, the touchpad sends\n\
  arrow keys. Click again for Enter.\n\
For more info: \`man beepy-kbd\`\
" 20 40

# Query for autoidle service
if monoset 127 whiptail --title "Idle Shutdown Service" --yesno "\
Enable automatic idle shutdown?\n\n\
* 5 minutes after last keypress\n\
* Won't shut down if SSH connected\n\
* Won't shut down running programs\n\n\
Run \`man beepy-idle\` for user guide including editing \
timeout, allowed programs, and enabling / disabling service\n\n\
Press Alt + Enter to switch Yes/No" --defaultno 20 40; then
	sudo systemctl enable beepy-idle.timer
	sudo systemctl start beepy-idle.timer
else
	sudo systemctl disable beepy-idle.service
	sudo systemctl disable beepy-idle.timer
fi

# impala information
monoset 127 whiptail --title "Network Configuration" --msgbox "\
Starting \`impala\` for network config\n\n\
Use arrow keys to move to New Nets tab and \
to highlight your network, then Space to \
start connecting.\n\n\
* Hold the Berry key for Meta mode \n\
  reference, including arrow keys.\n\
* Hold the Sym key for Symbol key \n\
  reference.\n\
* Press the Back key for Escape,\n\
  or to exit Meta mode. \n\
* Press Q to exit \`impala\`.\
" 20 40

echo "Waiting for NetworkManager..."
for i in $(seq 1 5); do
	if systemctl --quiet is-active NetworkManager; then
		sudo impala ||:
		sudo rm -f /etc/profile.d/zz-interactive-firstboot.sh ||:
		exit 0
	fi
	sleep 1
done

)
EOF
chmod +x /etc/profile.d/zz-interactive-firstboot.sh

# Expand root filesystem
whiptail --infobox "Expanding root filesystem to fill SD card" 20 40
raspi-config --expand-rootfs

# Disable remounting of boot partition
sed -i '/\/boot\/firmware/ s/^/# /' \
	/etc/fstab

# Disable raspi-config automatic service to save boot time
whiptail --infobox "Optimizing boot services" 20 40
systemctl daemon-reload
systemctl disable raspi-config

# Update firmware if required
/usr/lib/userconf-pi/beepy-firstboot-update
whiptail --infobox "Beepy set up complete, rebooting" 20 40
chvt "$ORIG_VT"
reboot
