name: Build

on:
  push:
    branches:
      - beepy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: True
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y docker qemu-user-static
    - name: Build image
      run: |
        sudo ./build-docker.sh
    - name : Upload image
      uses: actions/upload-artifact@v3
      with:
        name: sdcard.img
        path: deploy/*-Beepy.img

